CC=cc
CFLAGS=-Wall
SDL_LIB = -L/opt/local/lib -lSDL2 -lSDL2_ttf -lgc
# -L/opt/X11/lib -lfontconfig
SDL_INCLUDE = -I/opt/local/include/
#-I/opt/X11/include/
LDFLAGS = $(SDL_LIB)

all: chessboard

chessboard: main.o
	$(CC) $< $(LDFLAGS) -o $@

main.o: main.c
	$(CC) -c $(CFLAGS) $(SDL_INCLUDE) $< 

clean:
	rm *.o && rm chessboard

