CC=cc
  
SDL_CFLAGS = $(shell sdl2-config --cflags)
SDL_LDFLAGS = $(shell sdl2-config --libs) -lSDL2_ttf

CFLAGS=-Wall $(SDL_CFLAGS)
LDFLAGS = -lgc $(SDL_LDFLAGS)

all: chessboard

chessboard: main.o
	$(CC) $< $(LDFLAGS) -o $@

main.o: main.c
	$(CC) $(CFLAGS) -c $< 

clean:
	rm *.o && rm chessboard

